services:
  logistic-optimization:
    image: etidahouse/logistic-optimization:latest
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    environment:
      FLOWS_CSV: data/flows.csv
      CELLS_CSV: data/cells.csv

  logistic-ui:
    image: etidahouse/logistic-ui:latest
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    environment:
      FLOWS_CSV: data/flows.csv
      CELLS_CSV: data/cells.csv
