name: CI Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Environment Variables
        run: env

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN}}

      - name: Set up Git Configuration
        run: |
          git config --global user.email "e-begon@hotmail.fr"
          git config --global user.name "etidahouse"

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Configure dockerhub release service account
        run: docker login -u "$DOCKER_USERNAME" --password "$DOCKER_TOKEN"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Release docker
        run: sh/ci-release
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
